{
 "title": "vLLM model",
 "description": "Monitoring vLLM Inference Server",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  {
   "title": "⏱︎ Average Response Time",
   "type": "stat",
   "description": "Average response time for questions and answers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$Response_Time_Sum/$Question_Count",
     "type": "math"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "histogram",
   "description": "Distribution of response time for questions and answers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select  (EXTRACT(EPOCH FROM age(kcma.create_time,kcmq.create_time))) AS Response_Time\r\nfrom km_chat_message_question kcmq \r\nleft join km_chat_message_answer kcma\r\non kcmq.id  = kcma.que_id\r\nwhere kcmq.create_time >=  $__timeFrom() AT TIME ZONE 'UTC' + INTERVAL '8 hours' AND kcma.create_time <= $__timeTo()  AT TIME ZONE 'UTC' + INTERVAL '8 hours'\r\nand LENGTH(kcma.message) != 0 and (score != 1 or score is null ) and (EXTRACT(EPOCH FROM age(kcma.create_time,kcmq.create_time)))>0"
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec"
    },
    {
     "expr": "rate(vllm:generation_tokens_total{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vllm:num_requests_running{model_name=\"$model_name\"}",
     "legendFormat": "Num Running"
    },
    {
     "expr": "vllm:num_requests_swapped{model_name=\"$model_name\"}",
     "legendFormat": "Num Swapped"
    },
    {
     "expr": "vllm:num_requests_waiting{model_name=\"$model_name\"}",
     "legendFormat": "Num Waiting"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{model_name=\"$model_name\"}",
     "legendFormat": "GPU Cache Usage"
    },
    {
     "expr": "vllm:cpu_cache_usage_perc{model_name=\"$model_name\"}",
     "legendFormat": "CPU Cache Usage"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:time_per_output_token_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}